baseurl = "/"
languageCode = "en-us"
title = ""
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[params]
    description = ""
    footer = ""
    custom_css = ["css/theme-override.css"]
